version: "3"

services:
  server:
    container_name: "PCCreator"
    build: ./Dockerfile.local
    ports:
      - 8040:8040
    depends_on:
      - db

  db:
    restart: always
    image: mongo:latest
    volumes:
      - ./.build/volumes/databases/mongo/data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}